### ISSUE TITLE
[META] Istanbul implementation

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5716]
Meta EIP https://eips.ethereum.org/EIPS/eip-1679

### Accepted EIPs

- [x] [EIP-152](https://github.com/ethereum/EIPs/pull/2129): Add Blake2 compression function F precompile https://github.com/ethereum/aleth/pull/5751
- [x] [EIP-1108](https://eips.ethereum.org/EIPS/eip-1108): Reduce alt_bn128 precompile gas costs https://github.com/ethereum/aleth/pull/5705
- [x] [EIP-1344](https://eips.ethereum.org/EIPS/eip-1344): Add ChainID opcode
  - [x] LegacyVM https://github.com/ethereum/aleth/pull/5696
  - [x] EVMC https://github.com/ethereum/evmc/pull/375
  - [x] aleth-interpreter https://github.com/ethereum/aleth/pull/5708
- [x] [EIP-1884](https://eips.ethereum.org/EIPS/eip-1884): Repricing for trie-size-dependent opcodes
  - [x] LegacyVM https://github.com/ethereum/aleth/pull/5700
  - [x] EVMC https://github.com/ethereum/evmc/pull/372
  - [x] aleth-interpreter https://github.com/ethereum/aleth/pull/5725
- [x] [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028): Calldata gas cost reduction https://github.com/ethereum/aleth/pull/5691
- [x] [EIP-2200](https://github.com/ethereum/EIPs/pull/2200): Rebalance net-metered SSTORE gas cost with consideration of SLOAD gas cost change
   - [x] LegacyVM https://github.com/ethereum/aleth/pull/5709
   - [x] aleth-interpreter https://github.com/ethereum/aleth/pull/5728

### Maintenance stuff
- [x] Ropsten config update https://github.com/ethereum/aleth/pull/5758
- [x] Mainnet config update
- [ ] ~~Account version support in config parsing, needed only if account versioning is activated https://github.com/ethereum/aleth/issues/5645~~
- [x] Support Istanbul in aleth-vm command line parameters https://github.com/ethereum/aleth/pull/5762

**Comment by gumb0** [comment]
Updated the categories according to the latest meta-EIP.

**Comment by fubuloubu** [comment]
Please note that per https://github.com/ethereum/EIPs/pull/2263, EIP-1344 was updated to return a uint64 field instead of uint256

**Comment by halfalicious** [comment]
@gumb0 I've started working on EIP1380 (reduced gas call to self)

**Comment by gumb0** [comment]
Moved Berlin fork stuff from the description here to https://github.com/ethereum/aleth/issues/5768
