### ISSUE TITLE
[META] Berlin implementation

### ISSUE THREAD

**Issue by gumb0** [ethereum/aleth#5768]
### Possible EIPs
- [ ] [EIP-663](https://eips.ethereum.org/EIPS/eip-663): Unlimited SWAP and DUP instructions
  - implementation in evmone https://github.com/ethereum/evmone/pull/98
- [ ] [EIP-1057](https://eips.ethereum.org/EIPS/eip-1057): ProgPoW, a Programmatic Proof-of-Work
  - Supported in [ethash library](https://github.com/chfast/ethash), but PoW engine switching logic not implemented yet.
- [ ] [EIP-1380](https://eips.ethereum.org/EIPS/eip-1380): Reduced gas cost for call to self
  - [ ] LegacyVM https://github.com/ethereum/aleth/pull/5752
  - [ ] aleth-interpreter https://github.com/ethereum/aleth/pull/5752
- [ ] [EIP-1962](https://eips.ethereum.org/EIPS/eip-1962): EC arithmetic and pairings with runtime definitions
- [ ] [EIP-1985](https://eips.ethereum.org/EIPS/eip-1985): Sane limits for certain EVM parameters
  - Not sure if anything needs to be done here
- [ ] [EIP-2045](https://eips.ethereum.org/EIPS/eip-2045): Particle gas costs for EVM opcodes
  - implementation in evmone https://github.com/ethereum/evmone/pull/101
- [ ] [EIP-2046](https://eips.ethereum.org/EIPS/eip-2046): Reduced gas cost for static calls made to precompiles 
  - [x] LegacyVM https://github.com/ethereum/aleth/pull/5699

### Maintenance stuff
- [ ] Ropsten config update
- [ ] Mainnet config update
- [ ] Support Berlin in aleth-vm command line parameters
